name: Run Recipe Test 
on:
  repository_dispatch:
    types: [run-recipe-test-command]
jobs:
  run-recipe-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the pull request branch
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Get changed files
        id: changed-files
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"

      # - name: Get the files changed in the Pull Request
        # id: changed-files
        # uses: jitterbit/get-changed-files@v1
        # continue-on-error: true

      # - name: Download bakeries.yaml
        # id: download-bakeries
        # run: |
          # curl https://raw.githubusercontent.com/pangeo-forge/bakery-database/main/bakeries.yaml -o ${GITHUB_WORKSPACE}/bakeries.yaml

      - name: Locate Pull Requests meta.yaml
        id: meta
        run: |
          for changed_file in ${{ steps.changed-files.outputs.all }}; do
            if [[ ${changed_file} =~ ^.*recipes\/.*meta\.(yml|yaml)$ ]];
            then
              echo "::set-output name=META_YAML::${changed_file}";
              exit 0
            fi
          done
          exit 1 # Fail - meta.yaml required
